# Generated by Django 5.2.8 on 2025-12-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='api.user'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.station'),
        ),
        migrations.AlterField(
            model_name='alertpollutant',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pollutants', to='api.alert'),
        ),
        migrations.AlterField(
            model_name='alertpollutant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alertpollutant',
            name='pollutant',
            field=models.CharField(choices=[('PM25', 'PM25'), ('PM10', 'PM10'), ('NO2', 'NO2'), ('O3', 'O3'), ('SO2', 'SO2'), ('CO', 'CO')], max_length=10),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_profile', to='api.user'),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.station'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('SENSOR', 'SENSOR'), ('METEO', 'METEO'), ('OTHER', 'OTHER')], max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='institutions', to='api.admin'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='station',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stations', to='api.admin'),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='station',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.institution'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AlertReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivers', to='api.alert')),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to='api.authuser')),
            ],
            options={
                'indexes': [models.Index(fields=['auth_user', 'alert'], name='api_alertre_auth_us_35dc85_idx')],
                'unique_together': {('auth_user', 'alert')},
            },
        ),
        migrations.CreateModel(
            name='StationConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulted_stations', to='api.authuser')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consults', to='api.station')),
            ],
            options={
                'indexes': [models.Index(fields=['auth_user', 'station'], name='api_station_auth_us_21dc8f_idx')],
                'unique_together': {('auth_user', 'station')},
            },
        ),
    ]
