"""
Django settings for core project.

This file defines the full configuration for the Django project,
including installed apps, middleware, database, authentication,
logging, internationalization, and integrations with DRF + JWT.

Automatically generated by 'django-admin startproject' and later
extended for VRISA backend architecture.
"""

import os
from pathlib import Path
from datetime import timedelta


"""
Resolve the base directory of the project.
Used for locating files relative to the project structure.
"""
BASE_DIR = Path(__file__).resolve().parent.parent


# ===============================================================
# SECURITY CONFIGURATION
# ===============================================================

"""
Secret key for cryptographic signing.
⚠️ Must be replaced with an environment variable in production.
"""
SECRET_KEY = 'django-insecure-8*jqdu+_m*ibs#nof3rj1w_@_&--b9h=igd17*+k@a(r@_6%%o'

"""
Debug mode should always be False in production, since it exposes
detailed error information that may compromise security.
"""
DEBUG = False  # Cambiar a False en producción

"""
Allowed hosts define which domains are permitted to access the server.
Using "*" allows any host (development only).
"""
ALLOWED_HOSTS = ["*"]


# ===============================================================
# APPLICATIONS
# ===============================================================

"""
Installed Django and third-party apps.
The order matters: 'core' must appear before 'api'.
"""
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',

    # Third-party
    'rest_framework',
    'rest_framework_gis',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',

    # Project apps
    'core',
    'api',
]


# ===============================================================
# MIDDLEWARE
# ===============================================================

"""
Middleware stack executed per request in order.
CORS middleware is enabled temporarily for React development.
"""
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Solo desarrollo
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ===============================================================
# REST FRAMEWORK CONFIGURATION
# ===============================================================

"""
Global DRF configuration:
- JWT authentication
- Default permissions
- Pagination
- Filters
- Renderers
- Exception handling
"""
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.StandardResultsSetPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z',
    'DATE_FORMAT': '%Y-%m-%d',
}


# ===============================================================
# SIMPLE JWT CONFIGURATION
# ===============================================================

"""
Configuration for JWT authentication:
- Token lifetime
- Rotation
- Claims
- Token types
"""
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}


# ===============================================================
# CORS CONFIGURATION (DEVELOPMENT ONLY)
# ===============================================================

"""
CORS (Cross-Origin Resource Sharing) settings.
Enabled for development to allow React frontend communication.
Must be restricted in production.
"""
CORS_ALLOW_ALL_ORIGINS = True  # Temporal para pruebas
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept', 'accept-encoding', 'authorization', 'content-type',
    'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
]


# ===============================================================
# AUTHENTICATION BACKENDS
# ===============================================================

"""
The project uses a custom authentication backend that authenticates
users via email. Django's default backend is kept as a fallback.
"""
AUTHENTICATION_BACKENDS = [
    'api.auth_backend.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',
]

"""
Specifies the custom user model used by the project.
"""
AUTH_USER_MODEL = 'api.User'


# ===============================================================
# LOGGING
# ===============================================================

"""
Logging configuration for debugging and auditing purposes.
Logs are written to both console and debug.log file.
"""
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },

    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },

    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },

    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


# ===============================================================
# URLS, WSGI, AND TEMPLATES
# ===============================================================

"""
Root URL configuration.
"""
ROOT_URLCONF = 'core.urls'

"""
Template engine configuration.
"""
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

"""
WSGI entry point for deployment.
"""
WSGI_APPLICATION = 'core.wsgi.application'


# ===============================================================
# DATABASE
# ===============================================================

"""
Database configuration using PostGIS.
Values are pulled from environment variables defined in Docker.
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get("DB_NAME", "vrisa"),
        'USER': os.environ.get("DB_USER", "vrisa_user"),
        'PASSWORD': os.environ.get("DB_PASSWORD", "vrisa_pass"),
        'HOST': os.environ.get("DB_HOST", "db"),
        'PORT': os.environ.get("DB_PORT", 5432),
    }
}


# ===============================================================
# PASSWORD VALIDATION
# ===============================================================

"""
Validators used to enforce strong password policies.
"""
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ===============================================================
# INTERNATIONALIZATION
# ===============================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ===============================================================
# STATIC FILES
# ===============================================================

"""
Static file configuration for serving CSS, JS, images, etc.
"""
STATIC_URL = 'static/'


# ===============================================================
# DEFAULT FIELD TYPE
# ===============================================================

"""
Default type for auto-generated primary keys.
"""
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True  # Temporal para React
