from django.contrib import admin
from django.contrib.gis import admin as geoadmin

from .models import (
    User, Admin, AuthUser,
    Institution, Station, Device,
    Alert, AlertPollutant,
    AlertReceive, StationConsult
)

"""
Admin configuration for all backend models.
Each admin class customizes how models appear in the Django admin panel,
including list displays, search fields, filters, ordering, and read-only fields.
"""


# -------------------------
# Custom User Admin
# -------------------------
"""
Admin interface for the main User model.
Allows searching by name/email and filtering by role/status.
"""
@admin.register(User)
class UserAdmin(admin.ModelAdmin):
    list_display = ("id", "name", "email", "role", "is_staff", "is_active", "created_at")
    search_fields = ("name", "email")
    list_filter = ("role", "is_staff", "is_active")
    ordering = ("-created_at",)
    readonly_fields = ("created_at", "updated_at")


# -------------------------
# Admin Profile
# -------------------------
"""
Admin interface for platform administrators (Admin model).
Displays linked user and access levels.
"""
@admin.register(Admin)
class AdminProfileAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "access_level", "created_at")
    search_fields = ("user__email", "user__name")


# -------------------------
# AuthUser Profile
# -------------------------
"""
Admin settings for AuthUser model.
Represents users with read-access permissions.
"""
@admin.register(AuthUser)
class AuthUserAdmin(admin.ModelAdmin):
    list_display = ("id", "user", "read_access", "created_at")
    search_fields = ("user__email",)


# -------------------------
# Institution
# -------------------------
"""
Admin interface for institutions.
Allows filtering by verification status and searching by name or admin email.
"""
@admin.register(Institution)
class InstitutionAdmin(admin.ModelAdmin):
    list_display = ("id", "name", "verified", "admin", "created_at")
    list_filter = ("verified",)
    search_fields = ("name", "admin__user__email")


# -------------------------
# Station (GeoModelAdmin)
# -------------------------
"""
Admin interface for Station model.
Uses GeoModelAdmin to display geographic fields.
"""
@admin.register(Station)
class StationAdmin(geoadmin.GeoModelAdmin):
    list_display = ("id", "name", "institution", "admin", "status", "installed_at")
    search_fields = ("name", "institution__name", "admin__user__email")
    list_filter = ("status",)
    readonly_fields = ("created_at", "updated_at")


# -------------------------
# Device
# -------------------------
"""
Admin settings for devices installed on stations.
Allows filtering by type and searching by serial number.
"""
@admin.register(Device)
class DeviceAdmin(admin.ModelAdmin):
    list_display = ("id", "serial_number", "type", "station", "install_date")
    list_filter = ("type",)
    search_fields = ("serial_number",)


# -------------------------
# Alert
# -------------------------
"""
Admin interface for alerts generated by stations.
Supports filtering by attended status and station.
"""
@admin.register(Alert)
class AlertAdmin(admin.ModelAdmin):
    list_display = ("id", "station", "attended", "alert_date")
    list_filter = ("attended", "station")
    search_fields = ("station__name",)


# -------------------------
# AlertPollutant
# -------------------------
"""
Admin settings for pollutants associated with alerts.
Displays pollutant type, level, and timestamp.
"""
@admin.register(AlertPollutant)
class AlertPollutantAdmin(admin.ModelAdmin):
    list_display = ("id", "alert", "pollutant", "level", "recorded_at")
    list_filter = ("pollutant",)
    search_fields = ("alert__station__name",)


# -------------------------
# M2M intermediate tables
# -------------------------
"""
Admin configuration for intermediate many-to-many models:
- AlertReceive: users receiving alerts
- StationConsult: users consulting stations
"""
@admin.register(AlertReceive)
class AlertReceiveAdmin(admin.ModelAdmin):
    list_display = ("id", "auth_user", "alert", "received_at")
    search_fields = ("auth_user__user__email", "alert__station__name")


@admin.register(StationConsult)
class StationConsultAdmin(admin.ModelAdmin):
    list_display = ("id", "auth_user", "station", "granted_at")
    search_fields = ("auth_user__user__email", "station__name")